name = "hex-matrix"
defaultTargets = ["HexMatrix"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "a47240943e925951a676d1a1c2f2a615ae68fdef"

[[lean_lib]]
name = "HexMatrix"
precompileModules = true
