name = "hex-matrix"
defaultTargets = ["HexMatrix"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBasic"
git = "https://github.com/leanprover/hex-basic.git"
rev = "da8a864cd17ccca780d8c76af403e88585bc4734"

[[lean_lib]]
name = "HexMatrix"
precompileModules = true
