name = "hex-matrix"
defaultTargets = ["HexMatrix"]

[[require]]
name = "HexBasic"
git = "https://github.com/kim-em/hex-basic.git"
rev = "40bc251f7a825a3927fc13309189b867316253c3"

[[lean_lib]]
name = "HexMatrix"
precompileModules = true
